# Site Settings
baseurl: ""
url : "https://sunny7516.github.io"

# Blog Settings
theme_settings :
  title : Developer Sonalog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.jpg
    username : Sona Hong
    description : The Blog for my Development Life!ğŸ–¤
    experience :
      - start : 2017-11-01
        end : 2020-10-30
        experience : í•˜ë‚˜íˆ¬ì–´, ì‚¬ë‚´ ì¸íŠ¸ë¼ë„· ê°œë°œ/ìš´ì˜
    skills : 
      - skill : Java, Spring framework, Linux, WEB/WAS, SQL, Redis
        value : 50  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "limbo001@naver.com"
    linkedin:  # Full URL 
    github: sunny7516
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
